---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-auto
  namespace: netology
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
...
