---
apiVersion: v1
kind: Service
metadata:
  name: svc14-task2
  namespace: netology
spec:
  type: NodePort
  selector:
    app: app14
  ports:
    - name: nginx
      protocol: TCP
      port: 9001
      targetPort: 80
      nodePort: 30001
    - name: multitool-http
      protocol: TCP
      port: 9002
      targetPort: 8080
      nodePort: 30002
...