---
apiVersion: v1
kind: Service
metadata:
  name: svc14-task1
  namespace: netology
spec:
  selector:
    app: app14
  ports:
    - name: nginx
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: multitool-http
      protocol: TCP
      port: 9002
      targetPort: 8080
...