---
apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
  namespace: netology
spec:
  selector:
    app: deploy34
  ports:
    - name: deploy34-nginx
      protocol: TCP
      port: 80
      targetPort: 80
...
